import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/constants";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: SITE_URL,                                   lastModified: new Date(), changeFrequency: "daily",   priority: 1   },
    { url: `${SITE_URL}/buy`,                          lastModified: new Date(), changeFrequency: "hourly",  priority: 0.9 },
    { url: `${SITE_URL}/rent`,                         lastModified: new Date(), changeFrequency: "hourly",  priority: 0.9 },
    { url: `${SITE_URL}/sold`,                         lastModified: new Date(), changeFrequency: "daily",   priority: 0.7 },
    { url: `${SITE_URL}/house-and-land`,               lastModified: new Date(), changeFrequency: "weekly",  priority: 0.8 },
    { url: `${SITE_URL}/off-market`,                   lastModified: new Date(), changeFrequency: "weekly",  priority: 0.7 },
    { url: `${SITE_URL}/suburbs`,                      lastModified: new Date(), changeFrequency: "weekly",  priority: 0.8 },
    { url: `${SITE_URL}/regions`,                      lastModified: new Date(), changeFrequency: "weekly",  priority: 0.7 },
    { url: `${SITE_URL}/agents`,                       lastModified: new Date(), changeFrequency: "weekly",  priority: 0.7 },
    { url: `${SITE_URL}/real-estate-agencies`,         lastModified: new Date(), changeFrequency: "weekly",  priority: 0.6 },
    { url: `${SITE_URL}/blog`,                         lastModified: new Date(), changeFrequency: "weekly",  priority: 0.7 },
    { url: `${SITE_URL}/research`,                     lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${SITE_URL}/price-guide`,                  lastModified: new Date(), changeFrequency: "weekly",  priority: 0.6 },
    { url: `${SITE_URL}/schools`,                      lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${SITE_URL}/mortgage-calculator`,          lastModified: new Date(), changeFrequency: "yearly",  priority: 0.6 },
    { url: `${SITE_URL}/stamp-duty-calculator`,        lastModified: new Date(), changeFrequency: "yearly",  priority: 0.6 },
    { url: `${SITE_URL}/borrowing-power-calculator`,   lastModified: new Date(), changeFrequency: "yearly",  priority: 0.6 },
    { url: `${SITE_URL}/rental-yield-calculator`,      lastModified: new Date(), changeFrequency: "yearly",  priority: 0.6 },
    { url: `${SITE_URL}/cgt-calculator`,               lastModified: new Date(), changeFrequency: "yearly",  priority: 0.6 },
    { url: `${SITE_URL}/refinancing-calculator`,       lastModified: new Date(), changeFrequency: "yearly",  priority: 0.6 },
    { url: `${SITE_URL}/appraisal`,                    lastModified: new Date(), changeFrequency: "yearly",  priority: 0.6 },
    { url: `${SITE_URL}/affordability-calculator`,     lastModified: new Date(), changeFrequency: "yearly",  priority: 0.6 },
    { url: `${SITE_URL}/best-suburbs`,                 lastModified: new Date(), changeFrequency: "weekly",  priority: 0.7 },
    { url: `${SITE_URL}/compare`,                      lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${SITE_URL}/find-your-suburb`,             lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${SITE_URL}/tools`,                        lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${SITE_URL}/insights`,                     lastModified: new Date(), changeFrequency: "daily",   priority: 0.8 },
    { url: `${SITE_URL}/search`,                       lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE_URL}/methodology`,                  lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE_URL}/data`,                         lastModified: new Date(), changeFrequency: "daily",   priority: 0.6 },
    { url: `${SITE_URL}/data-updates`,                 lastModified: new Date(), changeFrequency: "weekly",  priority: 0.5 },
    { url: `${SITE_URL}/site-map`,                     lastModified: new Date(), changeFrequency: "monthly", priority: 0.4 },
    { url: `${SITE_URL}/states`,                       lastModified: new Date(), changeFrequency: "weekly",  priority: 0.6 },
    { url: `${SITE_URL}/postcodes`,                    lastModified: new Date(), changeFrequency: "weekly",  priority: 0.6 },
    { url: `${SITE_URL}/market-reports`,               lastModified: new Date(), changeFrequency: "weekly",  priority: 0.7 },
    { url: `${SITE_URL}/rba-cash-rate`,                lastModified: new Date(), changeFrequency: "weekly",  priority: 0.6 },
    { url: `${SITE_URL}/glossary`,                     lastModified: new Date(), changeFrequency: "monthly", priority: 0.5 },
    { url: `${SITE_URL}/guides`,                       lastModified: new Date(), changeFrequency: "weekly",  priority: 0.8 },
    { url: `${SITE_URL}/find-an-expert`,               lastModified: new Date(), changeFrequency: "monthly", priority: 0.6 },
    { url: `${SITE_URL}/first-home-buyers`,            lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${SITE_URL}/selling`,                      lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${SITE_URL}/upgrading`,                    lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${SITE_URL}/investing`,                    lastModified: new Date(), changeFrequency: "monthly", priority: 0.7 },
    { url: `${SITE_URL}/about`,                        lastModified: new Date(), changeFrequency: "yearly",  priority: 0.5 },
    { url: `${SITE_URL}/contact`,                      lastModified: new Date(), changeFrequency: "yearly",  priority: 0.5 },
    { url: `${SITE_URL}/privacy`,                      lastModified: new Date(), changeFrequency: "yearly",  priority: 0.3 },
  ];
}
