/**
 * Maps abbreviated Australian LGA names (as stored in the `region` field, sourced
 * from the Matthew Proctor postcode dataset) to their full official council names.
 *
 * The source CSV stores short-form names like "Redland" or "Moreton Bay".
 * The full official names (used by ABS and the councils themselves) are
 * "Redland City Council" and "Moreton Bay Regional Council" respectively.
 *
 * Usage:
 *   import { fullLgaName } from "@/lib/utils/lga-names";
 *   fullLgaName("Redland")        // → "Redland City Council"
 *   fullLgaName("Queensland")     // → "Queensland" (state names pass through)
 *   fullLgaName("Unknown suburb") // → "Unknown suburb" (unknown names pass through)
 */

const LGA_MAP: Record<string, string> = {
  // ── Queensland ──────────────────────────────────────────────────────────────
  "Brisbane":            "Brisbane City Council",
  "Redland":             "Redland City Council",
  "Redland City":        "Redland City Council",
  "Logan":               "Logan City Council",
  "Logan City":          "Logan City Council",
  "Gold Coast":          "Gold Coast City Council",
  "Gold Coast City":     "Gold Coast City Council",
  "Ipswich":             "Ipswich City Council",
  "Moreton Bay":         "Moreton Bay Regional Council",
  "Sunshine Coast":      "Sunshine Coast Council",
  "Noosa":               "Noosa Shire Council",
  "Scenic Rim":          "Scenic Rim Regional Council",
  "Lockyer Valley":      "Lockyer Valley Regional Council",
  "Somerset":            "Somerset Regional Council",
  "Toowoomba":           "Toowoomba Regional Council",
  "Western Downs":       "Western Downs Regional Council",
  "Maranoa":             "Maranoa Regional Council",
  "Darling Downs":       "Darling Downs Regional Council",
  "South Burnett":       "South Burnett Regional Council",
  "North Burnett":       "North Burnett Regional Council",
  "Gympie":              "Gympie Regional Council",
  "Fraser Coast":        "Fraser Coast Regional Council",
  "Bundaberg":           "Bundaberg Regional Council",
  "Gladstone":           "Gladstone Regional Council",
  "Rockhampton":         "Rockhampton Regional Council",
  "Central Highlands":   "Central Highlands Regional Council",
  "Isaac":               "Isaac Regional Council",
  "Mackay":              "Mackay Regional Council",
  "Whitsunday":          "Whitsunday Regional Council",
  "Burdekin":            "Burdekin Shire Council",
  "Charters Towers":     "Charters Towers Regional Council",
  "Hinchinbrook":        "Hinchinbrook Shire Council",
  "Townsville":          "Townsville City Council",
  "Palm Island":         "Palm Island Aboriginal Shire Council",
  "Cassowary Coast":     "Cassowary Coast Regional Council",
  "Cairns":              "Cairns Regional Council",
  "Douglas":             "Douglas Shire Council",
  "Tablelands":          "Tablelands Regional Council",
  "Mareeba":             "Mareeba Shire Council",
  "Cook":                "Cook Shire Council",
  "Weipa":               "Weipa Town Authority",
  "Hope Vale":           "Hope Vale Aboriginal Shire Council",
  "Lockhart River":      "Lockhart River Aboriginal Shire Council",
  "Aurukun":             "Aurukun Shire Council",
  "Napranum":            "Napranum Aboriginal Shire Council",
  "Mount Isa":           "Mount Isa City Council",
  "Burke":               "Burke Shire Council",
  "Carpentaria":         "Carpentaria Shire Council",
  "Cloncurry":           "Cloncurry Shire Council",
  "McKinlay":            "McKinlay Shire Council",
  "Doomadgee":           "Doomadgee Aboriginal Shire Council",
  "Mornington":          "Mornington Shire Council",
  "Longreach":           "Longreach Regional Council",
  "Barcaldine":          "Barcaldine Regional Council",
  "Blackall-Tambo":      "Blackall-Tambo Regional Council",
  "Boulia":              "Boulia Shire Council",
  "Barcoo":              "Barcoo Shire Council",
  "Quilpie":             "Quilpie Shire Council",
  "Bulloo":              "Bulloo Shire Council",
  "Murweh":              "Murweh Shire Council",
  "Paroo":               "Paroo Shire Council",

  // ── New South Wales ─────────────────────────────────────────────────────────
  "Albury":              "Albury City Council",
  "Armidale":            "Armidale Regional Council",
  "Ballina":             "Ballina Shire Council",
  "Bayside":             "Bayside Council",
  "Bega Valley":         "Bega Valley Shire Council",
  "Bellingen":           "Bellingen Shire Council",
  "Berrigan":            "Berrigan Shire Council",
  "Blacktown":           "Blacktown City Council",
  "Blue Mountains":      "Blue Mountains City Council",
  "Bogan":               "Bogan Shire Council",
  "Bourke":              "Bourke Shire Council",
  "Broken Hill":         "City of Broken Hill",
  "Byron":               "Byron Shire Council",
  "Campbelltown":        "Campbelltown City Council",
  "Canterbury-Bankstown":"Canterbury-Bankstown City Council",
  "Central Coast":       "Central Coast Council",
  "Cessnock":            "Cessnock City Council",
  "Clarence Valley":     "Clarence Valley Council",
  "Cobar":               "Cobar Shire Council",
  "Coffs Harbour":       "Coffs Harbour City Council",
  "Cumberland":          "Cumberland Council",
  "Dubbo":               "Dubbo Regional Council",
  "Dungog":              "Dungog Shire Council",
  "Fairfield":           "Fairfield City Council",
  "Forbes":              "Forbes Shire Council",
  "Georges River":       "Georges River Council",
  "Gilgandra":           "Gilgandra Shire Council",
  "Glen Innes":          "Glen Innes Severn Council",
  "Hawkesbury":          "Hawkesbury City Council",
  "Hay":                 "Hay Shire Council",
  "Hills":               "The Hills Shire Council",
  "Hornsby":             "Hornsby Shire Council",
  "Hunters Hill":        "Hunters Hill Council",
  "Inner West":          "Inner West Council",
  "Inverell":            "Inverell Shire Council",
  "Kempsey":             "Kempsey Shire Council",
  "Kiama":               "Kiama Municipal Council",
  "Ku-ring-gai":         "Ku-ring-gai Council",
  "Kyogle":              "Kyogle Council",
  "Lake Macquarie":      "Lake Macquarie City Council",
  "Lane Cove":           "Lane Cove Council",
  "Leeton":              "Leeton Shire Council",
  "Lismore":             "Lismore City Council",
  "Lithgow":             "Lithgow City Council",
  "Liverpool":           "Liverpool City Council",
  "Liverpool Plains":    "Liverpool Plains Shire Council",
  "Maitland":            "Maitland City Council",
  "Mid-Coast":           "Mid-Coast Council",
  "Mid-Western":         "Mid-Western Regional Council",
  "Moree Plains":        "Moree Plains Shire Council",
  "Mosman":              "Mosman Municipal Council",
  "Murray River":        "Murray River Council",
  "Muswellbrook":        "Muswellbrook Shire Council",
  "Narrabri":            "Narrabri Shire Council",
  "Newcastle":           "Newcastle City Council",
  "North Sydney":        "North Sydney Council",
  "Northern Beaches":    "Northern Beaches Council",
  "Oberon":              "Oberon Council",
  "Orange":              "Orange City Council",
  "Parramatta":          "City of Parramatta",
  "Penrith":             "Penrith City Council",
  "Port Macquarie":      "Port Macquarie-Hastings Council",
  "Port Stephens":       "Port Stephens Council",
  "Queanbeyan-Palerang": "Queanbeyan-Palerang Regional Council",
  "Randwick":            "Randwick City Council",
  "Richmond Valley":     "Richmond Valley Council",
  "Ryde":                "City of Ryde",
  "Shellharbour":        "Shellharbour City Council",
  "Singleton":           "Singleton Council",
  "Snowy Monaro":        "Snowy Monaro Regional Council",
  "Snowy Mountains":     "Snowy Mountains Council",
  "Strathfield":         "Strathfield Council",
  "Sutherland":          "Sutherland Shire Council",
  "Sydney":              "City of Sydney",
  "Tamworth":            "Tamworth Regional Council",
  "Tenterfield":         "Tenterfield Shire Council",
  "Tweed":               "Tweed Shire Council",
  "Upper Hunter":        "Upper Hunter Shire Council",
  "Upper Lachlan":       "Upper Lachlan Shire Council",
  "Uralla":              "Uralla Shire Council",
  "Wagga Wagga":         "Wagga Wagga City Council",
  "Warrumbungle":        "Warrumbungle Shire Council",
  "Waverley":            "Waverley Council",
  "Weddin":              "Weddin Shire Council",
  "Willoughby":          "Willoughby City Council",
  "Wollondilly":         "Wollondilly Shire Council",
  "Wollongong":          "Wollongong City Council",
  "Woollahra":           "Woollahra Municipal Council",

  // ── Victoria ────────────────────────────────────────────────────────────────
  "Alpine":              "Alpine Shire Council",
  "Ararat":              "Ararat Rural City Council",
  "Ballarat":            "City of Ballarat",
  "Banyule":             "Banyule City Council",
  "Bass Coast":          "Bass Coast Shire Council",
  "Baw Baw":             "Baw Baw Shire Council",
  "Bayside (Vic)":       "City of Bayside",
  "Benalla":             "Benalla Rural City Council",
  "Boroondara":          "City of Boroondara",
  "Brimbank":            "City of Brimbank",
  "Campaspe":            "Campaspe Shire Council",
  "Cardinia":            "Cardinia Shire Council",
  "Casey":               "City of Casey",
  "Central Goldfields":  "Central Goldfields Shire Council",
  "Colac-Otway":         "Colac-Otway Shire Council",
  "Corangamite":         "Corangamite Shire Council",
  "Darebin":             "City of Darebin",
  "East Gippsland":      "East Gippsland Shire Council",
  "Frankston":           "Frankston City Council",
  "Gannawarra":          "Gannawarra Shire Council",
  "Glen Eira":           "City of Glen Eira",
  "Glenelg":             "Glenelg Shire Council",
  "Golden Plains":       "Golden Plains Shire Council",
  "Greater Bendigo":     "City of Greater Bendigo",
  "Greater Dandenong":   "City of Greater Dandenong",
  "Greater Geelong":     "City of Greater Geelong",
  "Greater Shepparton":  "City of Greater Shepparton",
  "Hepburn":             "Hepburn Shire Council",
  "Hindmarsh":           "Hindmarsh Shire Council",
  "Hobsons Bay":         "City of Hobsons Bay",
  "Horsham":             "Horsham Rural City Council",
  "Hume":                "City of Hume",
  "Indigo":              "Indigo Shire Council",
  "Kingston":            "City of Kingston",
  "Knox":                "City of Knox",
  "Latrobe":             "Latrobe City Council",
  "Loddon":              "Loddon Shire Council",
  "Macedon Ranges":      "Macedon Ranges Shire Council",
  "Manningham":          "City of Manningham",
  "Mansfield":           "Mansfield Shire Council",
  "Maribyrnong":         "City of Maribyrnong",
  "Maroondah":           "Maroondah City Council",
  "Melbourne":           "City of Melbourne",
  "Melton":              "City of Melton",
  "Merri-bek":           "Merri-bek City Council",
  "Mildura":             "Mildura Rural City Council",
  "Mitchell":            "Mitchell Shire Council",
  "Monash":              "City of Monash",
  "Moonee Valley":       "City of Moonee Valley",
  "Moorabool":           "Moorabool Shire Council",
  "Moreland":            "City of Moreland",
  "Mornington Peninsula":"Mornington Peninsula Shire Council",
  "Mount Alexander":     "Mount Alexander Shire Council",
  "Moyne":               "Moyne Shire Council",
  "Murrindindi":         "Murrindindi Shire Council",
  "Nillumbik":           "Nillumbik Shire Council",
  "Northern Grampians":  "Northern Grampians Shire Council",
  "Port Phillip":        "City of Port Phillip",
  "Pyrenees":            "Pyrenees Shire Council",
  "Queenscliffe":        "Borough of Queenscliffe",
  "South Gippsland":     "South Gippsland Shire Council",
  "Southern Grampians":  "Southern Grampians Shire Council",
  "Stonnington":         "City of Stonnington",
  "Strathbogie":         "Strathbogie Shire Council",
  "Surf Coast":          "Surf Coast Shire Council",
  "Swan Hill":           "Swan Hill Rural City Council",
  "Towong":              "Towong Shire Council",
  "Wangaratta":          "Rural City of Wangaratta",
  "Warrnambool":         "Warrnambool City Council",
  "Wellington":          "Wellington Shire Council",
  "West Wimmera":        "West Wimmera Shire Council",
  "Whitehorse":          "City of Whitehorse",
  "Whittlesea":          "City of Whittlesea",
  "Wodonga":             "Wodonga City Council",
  "Wyndham":             "City of Wyndham",
  "Yarra":               "City of Yarra",
  "Yarra Ranges":        "Yarra Ranges Council",
  "Yarriambiack":        "Yarriambiack Shire Council",

  // ── Western Australia ────────────────────────────────────────────────────────
  "Albany":              "City of Albany",
  "Armadale":            "City of Armadale",
  "Augusta-Margaret River":"Shire of Augusta-Margaret River",
  "Bayswater":           "City of Bayswater",
  "Belmont":             "City of Belmont",
  "Bunbury":             "City of Bunbury",
  "Busselton":           "City of Busselton",
  "Cambridge":           "Town of Cambridge",
  "Canning":             "City of Canning",
  "Claremont":           "Town of Claremont",
  "Cockburn":            "City of Cockburn",
  "Cottesloe":           "Town of Cottesloe",
  "East Fremantle":      "Town of East Fremantle",
  "Fremantle":           "City of Fremantle",
  "Geraldton":           "City of Greater Geraldton",
  "Gosnells":            "City of Gosnells",
  "Joondalup":           "City of Joondalup",
  "Kalamunda":           "City of Kalamunda",
  "Kalgoorlie-Boulder":  "City of Kalgoorlie-Boulder",
  "Kelmscott":           "Shire of Serpentine-Jarrahdale",
  "Kellerberrin":        "Shire of Kellerberrin",
  "Mandurah":            "City of Mandurah",
  "Melville":            "City of Melville",
  "Mosman Park":         "Town of Mosman Park",
  "Mundaring":           "Shire of Mundaring",
  "Murray":              "Shire of Murray",
  "Nedlands":            "City of Nedlands",
  "Peppermint Grove":    "Shire of Peppermint Grove",
  "Perth":               "City of Perth",
  "Rockingham":          "City of Rockingham",
  "Serpentine-Jarrahdale":"Shire of Serpentine-Jarrahdale",
  "South Perth":         "City of South Perth",
  "Stirling":            "City of Stirling",
  "Subiaco":             "City of Subiaco",
  "Swan":                "City of Swan",
  "Victoria Park":       "Town of Victoria Park",
  "Vincent":             "City of Vincent",
  "Wanneroo":            "City of Wanneroo",

  // ── South Australia ─────────────────────────────────────────────────────────
  "Adelaide":            "City of Adelaide",
  "Adelaide Hills":      "Adelaide Hills Council",
  "Alexandrina":         "Alexandrina Council",
  "Barossa":             "Barossa Council",
  "Burnside":            "City of Burnside",
  "Campbelltown (SA)":   "City of Campbelltown",
  "Charles Sturt":       "City of Charles Sturt",
  "Clare and Gilbert Valleys":"Clare and Gilbert Valleys Council",
  "Copper Coast":        "Copper Coast Council",
  "Flinders Ranges":     "Flinders Ranges Council",
  "Gawler":              "Town of Gawler",
  "Holdfast Bay":        "City of Holdfast Bay",
  "Light":               "Light Regional Council",
  "Marion":              "City of Marion",
  "Mid Murray":          "Mid Murray Council",
  "Mitcham":             "City of Mitcham",
  "Mount Barker":        "District Council of Mount Barker",
  "Mount Gambier":       "City of Mount Gambier",
  "Murray Bridge":       "Rural City of Murray Bridge",
  "Norwood Payneham":    "City of Norwood Payneham and St Peters",
  "Onkaparinga":         "City of Onkaparinga",
  "Playford":            "City of Playford",
  "Port Adelaide Enfield":"City of Port Adelaide Enfield",
  "Port Augusta":        "City of Port Augusta",
  "Port Pirie":          "City of Port Pirie",
  "Prospect":            "City of Prospect",
  "Roxby Downs":         "Municipal Council of Roxby Downs",
  "Salisbury":           "City of Salisbury",
  "Tea Tree Gully":      "City of Tea Tree Gully",
  "Unley":               "City of Unley",
  "Victor Harbor":       "City of Victor Harbor",
  "Walkerville":         "Corporation of the Town of Walkerville",
  "West Torrens":        "City of West Torrens",
  "Whyalla":             "City of Whyalla",
  "Yankalilla":          "District Council of Yankalilla",

  // ── Tasmania ────────────────────────────────────────────────────────────────
  "Brighton":            "Brighton Council",
  "Central Coast (Tas)": "Central Coast Council",
  "Central Highlands (Tas)":"Central Highlands Council",
  "Clarence":            "Clarence City Council",
  "Derwent Valley":      "Derwent Valley Council",
  "Devonport":           "City of Devonport",
  "Dorset":              "Dorset Council",
  "Flinders (Tas)":      "Flinders Council",
  "George Town":         "George Town Council",
  "Glamorgan-Spring Bay":"Glamorgan-Spring Bay Council",
  "Glenorchy":           "City of Glenorchy",
  "Hobart":              "City of Hobart",
  "Huon Valley":         "Huon Valley Council",
  "Kentish":             "Kentish Council",
  "King Island":         "King Island Council",
  "Kingborough":         "Kingborough Council",
  "Latrobe (Tas)":       "Latrobe Council",
  "Launceston":          "City of Launceston",
  "Meander Valley":      "Meander Valley Council",
  "Northern Midlands":   "Northern Midlands Council",
  "Sorell":              "Sorell Council",
  "Southern Midlands":   "Southern Midlands Council",
  "Tasman":              "Tasman Council",
  "Waratah-Wynyard":     "Waratah-Wynyard Council",
  "West Coast":          "West Coast Council",
  "West Tamar":          "West Tamar Council",

  // ── Northern Territory ──────────────────────────────────────────────────────
  "Darwin":              "City of Darwin",
  "Litchfield":          "Litchfield Council",
  "Palmerston":          "City of Palmerston",

  // ── ACT ─────────────────────────────────────────────────────────────────────
  "Canberra":            "City of Canberra",
};

/** State names — these should pass through unchanged (not LGA names) */
const STATE_NAMES = new Set([
  "Queensland",
  "New South Wales",
  "Victoria",
  "Western Australia",
  "South Australia",
  "Tasmania",
  "Northern Territory",
  "Australian Capital Territory",
  "ACT",
]);

/**
 * Returns the full official council name for an LGA abbreviation,
 * or the raw value if the LGA is not in the lookup table.
 */
export function fullLgaName(region: string): string {
  if (!region || STATE_NAMES.has(region)) return region;
  return LGA_MAP[region] ?? region;
}
